; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60610.1 

	TITLE	C:\code\TEA\teastest\teastest.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4521	DB	'Hello World!', 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_puts:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv66 = -8						; size = 4
_fResult$ = -1						; size = 1
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_main	PROC
; File c:\code\tea\teastest\teastest.cpp
; Line 8
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 9
	push	OFFSET $SG4521
	call	_puts
	add	esp, 4
; Line 10
	cmp	DWORD PTR _argc$[ebp], 0
	jle	SHORT $LN3@main
	mov	DWORD PTR tv66[ebp], 1
	jmp	SHORT $LN4@main
$LN3@main:
	mov	DWORD PTR tv66[ebp], 0
$LN4@main:
	mov	al, BYTE PTR tv66[ebp]
	mov	BYTE PTR _fResult$[ebp], al
; Line 11
	xor	eax, eax
; Line 12
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
