//-----------------------------------------------------------------------
// <copyright file="Keyword.cs" company="Jon Rowlett">
//     Copyright (C) Jon Rowlett. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace TEAC
{
    /// <summary>
    /// Language keyword enum.
    /// </summary>
    internal enum Keyword
    {
        Dot,
        LeftParen,
        RightParen,
        LeftBracket,
        RightBracket,
        SemiColon,
        Colon,
        Equals,
        Assign,
        GreaterThan,
        GreaterThanOrEquals,
        LessThan,
        LessThanOrEquals,
        NotEqual,
        Comma,
        Address,
        Pointer,
        Star,
        Plus,
        Minus,
        Slash,
        Abstract,
        And,
        Array,
        Begin,
        Case,
        Class,
        Const,
        Constructor,
        Delete,
        Destructor,
        Div,
        Do,
        DownTo,
        Else,
        End,
        Extern,
        False,
        For,
        Function,
        If,
        In,
        Inherited,
        Interface,
        Mod,
        Namespace,
        New,
        Nil,
        Not,
        Of,
        Or,
        Packed,
        Private,
        Procedure,
        Program,
        Protected,
        Public,
        Record,
        Repeat,
        Set,
        Static,
        Then,
        To,
        True,
        Type,
        Until,
        Uses,
        Var,
        Virtual,
        While
    }
}