//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tea.Language.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TEAC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }        
        
        /// <summary>
        ///   Looks up a localized string similar to end of file..
        /// </summary>
        internal static string Parser_EndOfFile {
            get {
                return ResourceManager.GetString("Parser_EndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected end of file..
        /// </summary>
        internal static string Parser_EndOfFileExpected {
            get {
                return ResourceManager.GetString("Parser_EndOfFileExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier was expected, not {0}..
        /// </summary>
        internal static string Parser_IdentifierExpected {
            get {
                return ResourceManager.GetString("Parser_IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword {0} was expected, not {1}..
        /// </summary>
        internal static string Parser_KeywordExpected {
            get {
                return ResourceManager.GetString("Parser_KeywordExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not expected..
        /// </summary>
        internal static string Parser_Unexpected {
            get {
                return ResourceManager.GetString("Parser_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment is not terminated..
        /// </summary>
        internal static string TokenReader_CommentNotTerminated {
            get {
                return ResourceManager.GetString("TokenReader_CommentNotTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numberic value is expected immediately after the #..
        /// </summary>
        internal static string TokenReader_NoDigitAfterHash {
            get {
                return ResourceManager.GetString("TokenReader_NoDigitAfterHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string literal is not terminated..
        /// </summary>
        internal static string TokenReader_StringNotTerminated {
            get {
                return ResourceManager.GetString("TokenReader_StringNotTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsupported char [{0}] was detected in the stream..
        /// </summary>
        internal static string TokenReader_UnsupportedChar {
            get {
                return ResourceManager.GetString("TokenReader_UnsupportedChar", resourceCulture);
            }
        }
    }
}
